apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: hello-fastapi
  newName: sidneckel/hello-fastapi-k8s
  newTag: f343432d438ce702b4cd1c491a1cc6817984ac98
