apiVersion: v1
kind: Service
metadata:
  name: hello-fastapi-service
spec:
  selector:
    app: hello-fastapi
  ports:
    - protocol: TCP
      port: 8000              # porta do Service (externa)
      targetPort: 8000      # porta do container FastAPI

